### ISSUE TITLE
Vuforia configuration

### ISSUE THREAD

**Issue by sfalihi** [wowmaking/react-native-unity#19]
react-native: 61.5.
Unity 2019.3..

Hello i got this error trying to build for android:

Error:Failed to resolve: :VuforiaWrapper:

it seems it needs more configuration at least for android to find vuforia library

Could you update your library or readme for ar support?

**Comment by enriqueao** [comment]
app/build.gradle
```
dependencies {
    ...
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation(name: 'VuforiaWrapper', ext:'aar')
}
```

on ./bulid.gradle
```
allprojects {
    repositories {
        ...
        flatDir {
            dirs "$rootDir/../android/UnityExport/unityLibrary/libs"
        }
    }
}
```
