### ISSUE TITLE
iOS: Could Not Open UnityFramework File

### ISSUE THREAD

**Issue by octopus8** [wowmaking/react-native-unity#20]
Thank you for such a great tool, but I am having issues with iOS. I have followed the directions as described and I am able to build the app, but when executing on my attached device, the app immediately closes and I see in the XCode console window:

2020-01-07 11:42:58.394334-1000 RNUnityApp[1286:367900] Built from '2019.3/staging' branch, Version '2019.3.0f3 (6c9e2bfd6f81)', Build type 'Release', Scripting Backend 'il2cpp'
no boot config - using default values 
(Filename:  Line: 152)

-> applicationDidFinishLaunching()
**[libil2cpp] ERROR: Could not open /var/containers/Bundle/Application/8F8973CB-8CAE-4FEF-81C8-397565656096/RNUnityApp.app/Frameworks/UnityFramework.framework/Data/Managed/Metadata/global-metadata.dat**
   IL2CPP initialization failed

XCode has changed since the instructions were made, but here is a screenshot of how UnityFramework was added to the project:

![Screenshot (66)](https://user-images.githubusercontent.com/4854583/71936853-b3aeaa00-314e-11ea-886c-8e6354adcafa.png)

**Comment by pangia** [comment]
Did you find the solution for this?

**Comment by mksbamford** [comment]
Click the Data folder, and tick UnityFramework under the Target Membership on the right side of the screen

**Comment by Natkarock** [comment]
> Click the Data folder, and tick UnityFramework under the Target Membership on the right side of the screen

Hello! Where is Data folder located?

**Comment by Natkarock** [comment]
> Did you find the solution for this?

Did you find the solution for this?))

**Comment by mksbamford** [comment]
![image](https://user-images.githubusercontent.com/2213612/86496352-fb686400-bd74-11ea-81ff-5da0afb4ebfc.png)

**Comment by LionelWang** [comment]
Did you find the solution for this?

**Comment by mksbamford** [comment]
Click the Data folder, and tick UnityFramework under the Target Membership on the right side of the screen
![image](https://user-images.githubusercontent.com/2213612/86496352-fb686400-bd74-11ea-81ff-5da0afb4ebfc.png)

**Comment by Jeff-RenderHeads** [comment]
<img width="287" alt="Screenshot 2020-07-22 at 19 50 47" src="https://user-images.githubusercontent.com/35527321/88210533-a6718c80-cc54-11ea-96af-77641c6c10ff.png">
When I export, both of mine are ticked. Is that correct?

**Comment by Phanani** [comment]
I am getting the same issue can anybody help me out Thanks In adavance.

[libil2cpp] ERROR: Could not open /private/var/containers/Bundle/Application/417AE17C-0AF4-4756-8D3C-DFC80EED3890/PhaniTest.app/Data/Managed/Metadata/global-metadata.dat
   IL2CPP initialization failed

**Comment by julien-tamade** [comment]
Hi, did anybody find a solution to this?

**Comment by Jeff-RenderHeads** [comment]
It's definitely related to that unity framework not being selected. We were trying to build it through azure dev ops and it wasn't being selected.

**Comment by rcornwal** [comment]
I've verified the Data folder is set to the correct target, but getting the same error

**Comment by LasLamos** [comment]
Were you able to resolve the error?
Im getting the same error message in a different unity project and would appreciate some tips.

**Comment by Jeff-RenderHeads** [comment]
Are you building via a CI or just straight xcode?

**Comment by LasLamos** [comment]
I'm building via Xcode.
I combined a Unity project with an Native iOS one (or rather Ionic, but im using the Xcode generated by Ionic.)

**Comment by kirtirc** [comment]
Hello all
i have a same problem do you find any solution 
Thanks in advance

**Comment by JohnyLisir** [comment]
> <img alt="Screenshot 2020-07-22 at 19 50 47" width="287" src="https://user-images.githubusercontent.com/35527321/88210533-a6718c80-cc54-11ea-96af-77641c6c10ff.png">
> 
> When I export, both of mine are ticked. Is that correct?

Im getting the same error message in a different unity project and would appreciate some tips.


then, i'm try add the code after  frameworkLoad ,it's ok
eg: 

UnityFramework* UnityFrameworkLoad()
{
    NSString* bundlePath = nil;
    bundlePath = [[NSBundle mainBundle] bundlePath];
    bundlePath = [bundlePath stringByAppendingString: @"/Frameworks/UnityFramework.framework"];

    NSBundle* bundle = [NSBundle bundleWithPath: bundlePath];
    if ([bundle isLoaded] == false) [bundle load];

    UnityFramework* ufw = [bundle.principalClass getInstance];
    if (![ufw appController])
    {
        // unity is not initialized
        [ufw setExecuteHeader: &_mh_execute_header];
    }
    
    [ufw setDataBundleId:"com.unity3d.framework"];  /////////add this code
    return ufw;
}

**Comment by omgmax** [comment]
any resolution?

**Comment by tyym1314** [comment]
> > <img alt="Screenshot 2020-07-22 at 19 50 47" width="287" src="https://user-images.githubusercontent.com/35527321/88210533-a6718c80-cc54-11ea-96af-77641c6c10ff.png">
> > When I export, both of mine are ticked. Is that correct?
> 
> Im getting the same error message in a different unity project and would appreciate some tips.
> 
> then, i'm try add the code after frameworkLoad ,it's ok eg:
> 
> UnityFramework* UnityFrameworkLoad() { NSString* bundlePath = nil; bundlePath = [[NSBundle mainBundle] bundlePath]; bundlePath = [bundlePath stringByAppendingString: @"/Frameworks/UnityFramework.framework"];
> 
> ```
> NSBundle* bundle = [NSBundle bundleWithPath: bundlePath];
> if ([bundle isLoaded] == false) [bundle load];
> 
> UnityFramework* ufw = [bundle.principalClass getInstance];
> if (![ufw appController])
> {
>     // unity is not initialized
>     [ufw setExecuteHeader: &_mh_execute_header];
> }
> 
> [ufw setDataBundleId:"com.unity3d.framework"];  /////////add this code
> return ufw;
> ```
> 
> }

It works for me! Thanks
