### ISSUE TITLE
Android: Build Failed related to missing :unityLibrary:

### ISSUE THREAD

**Issue by sdsmnc221** [wowmaking/react-native-unity#24]
Hello, first of all thank you so much for creating this package along with a very detailed to make Unity works with React Native for both platforms!

Unfortunately, I can't seem to get it to work, on both iOS and Android. I've clone your example repo, and also tried to start building my app from scratch, but I always received Build Failed. I'll talk about my issue on Android first.

So I created a basic React Native app, I ran it on Android and it worked fine.

Then I installed your package (npm i --save ...), I immediately received a Build failed error:

<img width="766" alt="Screenshot 2020-02-05 at 17 43 39" src="https://user-images.githubusercontent.com/26313690/73927216-4028c580-48d1-11ea-90df-4c7586fbe650.png">

Well maybe it was because I didn't configure anything yet. So I followed your docs for Android and configured everything just like what was said in the docs. Except for parts related to unityLibrary (especially the last step **Remove <intent-filter>...</intent-filter> from AndroidManifest.xml at unityLibrary to leave only integrated version**), I was kinda confused because I didn't have anything unityLibrary related in the project...

I tried to build the app after the configs, and yet another error:

<img width="629" alt="Screenshot 2020-02-06 at 11 02 25" src="https://user-images.githubusercontent.com/26313690/73927430-b2010f00-48d1-11ea-8ca4-843edc821b22.png">

So, to resume, this missing :unityLibrary: bugged me. And I don't know whether should I build my Unity project for Android first to make it to work (already did, but still nothing changed).

I'm kinda new to this, so I don't know how to figure this out by myself. If I could get your helps to make this work, I would appreciate it a lot. Thanks!

**Comment by pascaldisse** [comment]
I had quite some trouble figuring this out as well. Unfortunately, the instructions for android seem to be incomplete.

Before you can do anything, you need to build from unity to `PROJECT_ROOT/unity/builds/android.`
**Make sure to select `Export Project` under build settings.**

Then, follow steps 1-6 of the readme for android. For Step 7 (setting up minSdk), you need to edit the minSdk version in
`PROJECT_ROOT/unity/builds/android/unityLibrary/build.gradle`:

```
    defaultConfig {
        minSdkVersion 19
        ...
    }
```

And for step 8, you need to remove `<intent-filter>...</intent-filter>` (and everything in between)  from `PROJECT_ROOT/unity/builds/android/unityLibrary/src/main/AndroidManifest.xml`.

**Comment by BhaktiugpMrAR** [comment]
> I had quite some trouble figuring this out as well. Unfortunately, the instructions for android seem to be incomplete.
> 
> Before you can do anything, you need to build from unity to `PROJECT_ROOT/unity/builds/android.`
> **Make sure to select `Export Project` under build settings.**
> 
> Then, follow steps 1-6 of the readme for android. For Step 7 (setting up minSdk), you need to edit the minSdk version in `PROJECT_ROOT/unity/builds/android/unityLibrary/build.gradle`:
> 
> ```
>     defaultConfig {
>         minSdkVersion 19
>         ...
>     }
> ```
> 
> And for step 8, you need to remove `<intent-filter>...</intent-filter>` (and everything in between) from `PROJECT_ROOT/unity/builds/android/unityLibrary/src/main/AndroidManifest.xml`.

Hi, already followed your guidance, but I still get error
`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :unityLibrary.
     Required by:
         project :app
      > Unable to find a matching variant of project :unityLibrary:
          - Variant 'debugApiElements' capability UnityReact1:unityLibrary:unspecified:
              - Incompatible attribute:
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
                  - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
          - Variant 'debugBundleElements' capability UnityReact1:unityLibrary:unspecified:
              - Incompatible attribute:
                  - Required org.gradle.usage 'java-api' and found incompatible value 'android-bundle'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' but no value provided.
                  - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
          - Variant 'debugMetadataElements' capability UnityReact1:unityLibrary:unspecified:
              - Incompatible attribute:
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Metadata'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
                  - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
                  - Required org.gradle.usage 'java-api' but no value provided.
          - Variant 'debugRuntimeElements' capability UnityReact1:unityLibrary:unspecified:
              - Incompatible attribute:
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
                  - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-runtime'.
          - Variant 'releaseApiElements' capability UnityReact1:unityLibrary:unspecified:
              - Incompatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
          - Variant 'releaseBundleElements' capability UnityReact1:unityLibrary:unspecified:
              - Incompatible attribute:
                  - Required org.gradle.usage 'java-api' and found incompatible value 'android-bundle'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' but no value provided.
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
          - Variant 'releaseMetadataElements' capability UnityReact1:unityLibrary:unspecified:
              - Incompatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Metadata'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Required org.gradle.usage 'java-api' but no value provided.
          - Variant 'releaseRuntimeElements' capability UnityReact1:unityLibrary:unspecified:
              - Incompatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-runtime'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :unityLibrary.
     Required by:
         project :app
      > Unable to find a matching variant of project :unityLibrary:
          - Variant 'debugApiElements' capability UnityReact1:unityLibrary:unspecified:
              - Incompatible attribute:
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
                  - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
          - Variant 'debugBundleElements' capability UnityReact1:unityLibrary:unspecified:
              - Incompatible attribute:
                  - Required org.gradle.usage 'java-api' and found incompatible value 'android-bundle'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' but no value provided.
                  - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
          - Variant 'debugMetadataElements' capability UnityReact1:unityLibrary:unspecified:
              - Incompatible attribute:
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Metadata'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
                  - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
                  - Required org.gradle.usage 'java-api' but no value provided.
          - Variant 'debugRuntimeElements' capability UnityReact1:unityLibrary:unspecified:
              - Incompatible attribute:
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
                  - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-runtime'.
          - Variant 'releaseApiElements' capability UnityReact1:unityLibrary:unspecified:
              - Incompatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
          - Variant 'releaseBundleElements' capability UnityReact1:unityLibrary:unspecified:
              - Incompatible attribute:
                  - Required org.gradle.usage 'java-api' and found incompatible value 'android-bundle'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' but no value provided.
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
          - Variant 'releaseMetadataElements' capability UnityReact1:unityLibrary:unspecified:
              - Incompatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Metadata'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Required org.gradle.usage 'java-api' but no value provided.
          - Variant 'releaseRuntimeElements' capability UnityReact1:unityLibrary:unspecified:
              - Incompatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-runtime'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at makeError (D:\Programs\nodejs\projects\UnityReact1\node_modules\execa\index.js:174:9)
    at D:\Programs\nodejs\projects\UnityReact1\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (D:\Programs\nodejs\projects\UnityReact1\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (D:\Programs\nodejs\projects\UnityReact1\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:9)`

It's just my first time using react native. i would be so thankful if you help me to fix this problem, thank u!

**Comment by ig4ever** [comment]
@sdsmnc221 if ur problem still occurs, try to build your unity project with 2019.3 version because the generated android project below 2019.3 version is a bit different. The unityLibrary folder will be generated automatically. If u still confuse u can download a "fixed" template project from here [](https://github.com/ig4ever/react-native-unity-example-master-fixed).
