### ISSUE TITLE
Execution failed for task ':unityLibrary:BuildIl2CppTask

### ISSUE THREAD

**Issue by komalharmale** [wowmaking/react-native-unity#33]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\TVDMUMKM375\Desktop\MyClassmate\UnityToReact\android\UnityExport\unityLibrary\build.gradle' line: 63

Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> NDK is not installed

**Comment by ambojialur** [comment]
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Build file 'C:\Users\TVDMUMKM375\Desktop\MyClassmate\UnityToReact\android\UnityExport\unityLibrary\build.gradle' line: 63
> 
> Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> 
> > NDK is not installed

**Has anyone found the solution to this?**

**Comment by kurtsergey** [comment]
Just install [NDK](https://developer.android.com/studio/projects/install-ndk)

**Comment by ambojialur** [comment]
> Just install [NDK](https://developer.android.com/studio/projects/install-ndk)

But still not working

**Comment by ambojialur** [comment]
**Solved!!**

Add ndkVersion same as in the android studio [project_root]/unity/builds/android/unityLibrary/build.gradle 

android { 
... 
ndkVersion = "21.3.6528147" 
... 
}

**Comment by dmitry-markevich** [comment]
We are working on post processing script than should replace ndk path of exported project to the path of Unity Editor`s ndk instance: https://github.com/wowmaking/react-native-unity/commit/e095a34e70b1e6286ec3caba0462ccbca1c016fa

This should fix such problems
