### ISSUE TITLE
'UnityFramework/UnityFramework.h' file not found

### ISSUE THREAD

**Issue by BunieVu** [wowmaking/react-native-unity#36]
<img width="1426" alt="Screen Shot 2022-10-26 at 13 44 09" src="https://user-images.githubusercontent.com/54257370/197953880-f26d4a4b-f131-490c-befa-8b86eb473f10.png">

I have followed your instructions but i'm getting this error in IOS.
Xccode version:  14.0.1
RN version: 0.70.4

**Comment by monkeyK1n9** [comment]
Hello @BunieVu , I am facing the same issue, did you find a solution?

**Comment by BunieVu** [comment]
> Hello @BunieVu , I am facing the same issue, did you find a solution?

i shared how to fix this issue in post: https://github.com/azesmway/react-native-unity/issues/52
